package ha.ecz.com.subscriberpanel.retrofit

data class myresponse (

        val propertyID : Int,
        val title : String,
        val description : String,
        val address : String,
        val streetName : String,
        val districtZone : String,
        val postalCode : String,
        val cityID : Int,
        val city : String,
        val propertyCategoryID : Int,
        val propertyCategory : String,
        val purposeID : Int,
        val unitID : Int,
        val purpose : String,
        val landArea : Int,
        val landAreaUnitID : Int,
        val landAreaUnit : String,
        val priceBudget : Int,
        val currencyID : Int,
        val currency : String,
        val latitude : Int,
        val longitude : Int,
        val privacy : Int,
        val isHot : Boolean,
        val isFeatured : Boolean,
        val isPromo : Boolean,
        val isPopOut : Boolean,
        val imageURL : String,
        val localAreaName : String,
        val active : Int,
        val subscriberID : Int,
        val createdDate : String,
        val createdBy : Int,
        val lastUpdated : String,
        val descriptionInText : String,
        val address_Component : String,
        val locationAlias : String,
        val subLocalityLevel : String,
        val frontImage : String,
        val message : String,
        val additionalImage : String,
        val amenities : String
)